knpu_oauth2_client:
    clients:
        spotify:
            type: spotify
            client_id: '%env(OAUTH_SPOTIFY_ID)%'
            client_secret: '%env(OAUTH_SPOTIFY_SECRET)%'
            redirect_route: spotify_callback
            redirect_params: {}
        strava:
            type: strava
            client_id: '%env(OAUTH_STRAVA_ID)%'
            client_secret: '%env(OAUTH_STRAVA_SECRET)%'
            redirect_route: strava_callback
            redirect_params: { }
